### ISSUE TITLE
speed up battle starts?

### ISSUE THREAD

**Issue by pwinckles** [Yukitty/CassetteBeasts-cat-qol#1]
I just tried this mod because I was hoping it would speed up the start of battles. When you've got a lot of moves that fire at the beginning of a battle, they can be excruciatingly slow to start. Removing the battle animations helps a little, but it doesn't reduce the times of moves like echolocation, custom starter, and status effect moves without animations. Just as an example, I had one monster with echolocation and custom starter triggering AP Boost, and the other with custom starter triggering Pumpkin Pie. Without this mod, it would take around 17 seconds for a battle to start. With this mod, it takes around 14 seconds.

I was wondering if you thought anything more could be done to speed things up, or if that was not possible.

Thank you for your work!

**Comment by Yukitty** [comment]
I'm aware that status effect animations are still terribly long. I haven't found a clean way to remedy this yet.

Other mods are available which can "fast forward" the entire battle system, and should effectively stack with skipped battle animations, but I can't get a link to share with you right now due to Mod Workshop's absolute instability.

**Comment by Yukitty** [comment]
Oh, uh. This was fixed in Release v1.7, it should be fine now. Status effect animations get skipped just like the rest of the moves.
